name: 'Build swu'
runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: 'Build index'
      run: deno run --allow-read=. --allow-write=./dist ${{ github.action_path }}/main.ts